# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'dockerwithmicroservices:$(build.buildNumber)'
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: docker build -t umamaheswareada/$(imageName) -f Dockerfile .
- script: docker login -u "umamaheswareada" -p "m@#E$#@550" docker.io